import type { PackageSections } from './interfaces';

/**
 * These will be rendered in the gaming section of the app. Each section has a name and a list of packages,
 * and will be put into its own tab. Each Section will be a different card in the tab of the gaming section.
 * To test general availability of all pkgnames besides the AUR packages, you can use the following command:
 * "pnpm check-pkglists", this will report missing packages (needs to be run on Garuda/Arch Linux with Chaotic-AUR enabled).
 */
export const gamingPackageLists: PackageSections = [
  {
    name: 'gaming.launchers',
    sections: [
      { name: 'Bottles', pkgname: ['bottles'], icon: 'bottles.svg', description: 'gaming.bottles' },
      { name: 'GameHub', pkgname: ['gamehub'], icon: 'gamehub.svg', description: 'gaming.gamehub' },
      {
        name: 'Heroic Games Launcher',
        pkgname: ['heroic-games-launcher-bin'],
        icon: 'heroic-icon.png',
        description: 'gaming.heroic',
      },
      { name: 'Itch', pkgname: ['itch-setup-bin'], icon: 'itch.svg', description: 'gaming.itch' },
      { name: 'Lutris', pkgname: ['lutris'], icon: 'lutris.png', description: 'gaming.lutris' },
      { name: 'Minigalaxy', pkgname: ['minigalaxy'], icon: 'minigalaxy.png', description: 'gaming.minigalaxy' },
      { name: 'Steam', pkgname: ['steam'], icon: 'steam.png', description: 'gaming.steamRuntime' },
    ],
  },
  {
    name: 'gaming.wine',
    sections: [
      { name: 'Boxtron', pkgname: ['boxtron'], icon: 'DOSBox.png', description: 'gaming.boxtron' },
      { name: 'Luxtorpeda', pkgname: ['luxtorpeda-git'], icon: 'proton.svg', description: 'gaming.luxtorpeda' },
      {
        name: 'ProtonGE-Custom',
        pkgname: ['proton-ge-custom-bin'],
        description: 'gaming.protonGeCustom',
      },
      {
        name: 'Proton CachyOS',
        pkgname: ['proton-cachyos'],
        description: 'gaming.protonCachyOS',
      },
      { name: 'Protontricks', pkgname: ['protontricks-git'], icon: 'proton.svg', description: 'gaming.protontricks' },
      { name: 'ProtonUp-Qt', pkgname: ['protonup-qt'], icon: 'protonup-qt.png', description: 'gaming.protonupQt' },
      { name: 'WINE Meta', pkgname: ['wine-meta'], icon: 'wine', description: 'gaming.wineMeta' },
      { name: 'WINE', pkgname: ['wine'], icon: 'wine', description: 'gaming.winePackage' },
      { name: 'WINE Staging', pkgname: ['wine-staging'], icon: 'wine', description: 'gaming.wineStaging' },
      { name: 'Winetricks', pkgname: ['winetricks'], icon: 'winetricks.png', description: 'gaming.winetricks' },
    ],
  },
  {
    name: 'gaming.tools',
    sections: [
      { name: 'DXVK', pkgname: ['dxvk-mingw-git'], description: 'gaming.dxvk' },
      {
        name: 'Gamemode',
        pkgname: ['gamemode', 'lib32-gamemode'],
        description: 'gaming.gamemode',
      },
      {
        name: 'Gamescope session (Steam)',
        pkgname: ['gamescope-session-steam-git'],
        icon: 'steam',
        description: 'gaming.gamescopeSessionSteam',
      },
      {
        name: 'Gamescope session',
        pkgname: ['gamescope-session-git'],
        icon: 'valve.png',
        description: 'gaming.gamescopeSession',
      },
      { name: 'Gamescope', pkgname: ['gamescope'], icon: 'valve.png', description: 'gaming.gamescope' },
      { name: 'LACT', pkgname: ['lact'], icon: 'lact.png', description: 'gaming.lact' },
      {
        name: 'MangoHud',
        pkgname: ['mangohud', 'lib32-mangohud'],
        icon: 'mangohud.png',
        description: 'gaming.mangohud',
      },
      {
        name: 'SteamTinkerLaunch',
        pkgname: ['steamtinkerlaunch'],
        icon: 'steam',
        description: 'gaming.steamtinkerlaunch',
      },
      {
        name: 'VR video player',
        pkgname: ['vr-video-player'],
        description: 'gaming.vrVideoPlayer',
      },
      { name: 'vkBasalt', pkgname: ['vkbasalt'], description: 'gaming.vkbasalt' },
    ],
  },
  {
    name: 'gaming.misc',
    sections: [
      { name: 'AntimicroX', pkgname: ['antimicrox'], icon: 'antimicrox.png', description: 'gaming.antimicrox' },
      { name: 'AnyDesk', pkgname: ['anydesk-bin'], icon: 'anydesk.svg', description: 'gaming.anydesk' },
      { name: 'CoreCtrl', pkgname: ['corectrl'], icon: 'corectrl.png', description: 'gaming.corectrl' },
      { name: 'Discord', pkgname: ['discord'], icon: 'discord.png', description: 'gaming.discord' },
      { name: 'DisplayCAL', pkgname: ['displaycal'], icon: 'displaycal.png', description: 'gaming.displaycal' },
      { name: 'DroidCam', pkgname: ['droidcam'], icon: 'droidcam.png', description: 'gaming.droidcam' },
      { name: 'EasyEffects', pkgname: ['easyeffects'], icon: 'easyeffects.svg', description: 'gaming.easyeffects' },
      { name: 'GOverlay', pkgname: ['goverlay'], icon: 'goverlay.png', description: 'gaming.goverlay' },
      { name: 'GWE', pkgname: ['gwe'], icon: 'gwe.png', description: 'gaming.gwe' },
      {
        name: 'Game Conqueror',
        pkgname: ['gameconqueror'],
        description: 'gaming.gameconqueror',
      },
      {
        name: 'Input remapper',
        pkgname: ['input-remapper-git'],
        description: 'gaming.inputRemapper',
      },
      {
        name: 'Keyboard visualizer',
        pkgname: ['keyboard-visualizer-git'],
        description: 'gaming.keyboardVisualizer',
      },
      { name: 'Mumble', pkgname: ['mumble'], icon: 'mumble.svg', description: 'gaming.mumble' },
      { name: 'Noisetorch', pkgname: ['noisetorch'], icon: 'noisetorch.png', description: 'gaming.noisetorch' },
      { name: 'Nyrna', pkgname: ['nyrna'], icon: 'nyrna.png', description: 'gaming.nyrna' },
      { name: 'OBS Studio', pkgname: ['obs-studio'], icon: 'obs.svg', description: 'gaming.obsStudio' },
      { name: 'OpenRGB', pkgname: ['openrgb'], icon: 'openrgb.png', description: 'gaming.openrgb' },
      { name: 'Oversteer', pkgname: ['oversteer'], icon: 'oversteer.svg', description: 'gaming.oversteer' },
      { name: 'Piper', pkgname: ['piper'], icon: 'piper.svg', description: 'gaming.piper' },
      {
        name: 'Polychromatic',
        pkgname: ['polychromatic'],
        icon: 'polychromatic_green.svg',
        description: 'gaming.polychromatic',
      },
      {
        name: 'Sc-controller',
        pkgname: ['sc-controller'],
        description: 'gaming.scController',
      },
      { name: 'SoundWire', pkgname: ['soundwire'], icon: 'soundwire.png', description: 'gaming.soundwire' },
      {
        name: 'StreamLink Twitch GUI',
        pkgname: ['streamlink-twitch-gui-bin'],
        icon: 'streamlink-twitch.png',
        description: 'gaming.streamlinkTwitchGui',
      },
      { name: 'VLC', pkgname: ['vlc'], icon: 'vlc.svg', description: 'gaming.vlc' },
    ],
  },
  {
    name: 'gaming.controllers',
    sections: [
      { name: 'BlueZ', pkgname: ['bluez'], icon: 'bluez.png', description: 'gaming.bluez' },
      {
        name: 'Xbox One dongle',
        pkgname: ['xone-dongle-firmware'],
        icon: 'xone.svg',
        description: 'gaming.xoneDongleFirmware',
      },
      { name: 'Xbox One/X/S', pkgname: ['xone-dkms-git'], icon: 'xone.svg', description: 'gaming.xoneDkms' },
      { name: 'Xboxdrv', pkgname: ['xboxdrv'], icon: 'xbox.svg', description: 'gaming.xboxdrv' },
      { name: 'XpadNeo', pkgname: ['xpadneo-dkms'], icon: 'xbox.svg', description: 'gaming.xpadneo' },
    ],
  },
  {
    name: 'gaming.games',
    sections: [
      {
        name: '0 A.D.',
        description:
          '3D and historically-based real-time strategy game, alpha stage. Based on the Age of Empires series.',
        url: 'https://play0ad.com/',
        pkgname: ['0ad'],
      },
      {
        name: 'Aisleriot',
        description: 'A collection of solitaire card games.',
        url: 'https://wiki.gnome.org/Apps/Aisleriot',
        pkgname: ['aisleriot'],
      },
      {
        name: 'Angband',
        description: 'Roguelike dungeon exploration game based on the writings of JRR Tolkien.',
        url: 'https://rephial.org/',
        pkgname: ['angband'],
      },
      {
        name: 'Armagetron Advanced',
        description: 'Tron Clone in 3D.',
        url: 'https://armagetronad.org/',
        pkgname: ['armagetronad'],
      },
      {
        name: 'Atomix',
        description: 'Build molecules out of single atoms.',
        url: 'https://wiki.gnome.org/Apps/Atomix',
        pkgname: ['atomix'],
      },
      {
        name: 'Augustus',
        description: 'An enhanced re-implementation of Caesar III.',
        url: 'https://github.com/Keriew/augustus',
        pkgname: ['augustus'],
      },
      {
        name: 'Barrage',
        description: "Violent ''point-and-click'' shooting game with nice effects.",
        url: 'https://lgames.sourceforge.net/Barrage/',
        pkgname: ['barrage'],
      },
      {
        name: 'Beneath a Steel Sky',
        description: 'point-and-click science fiction thriller set in a bleak vision of the future.',
        url: 'https://revolution.co.uk/games_catalog/beneath-a-steel-sky/',
        pkgname: ['bass'],
      },
      {
        name: 'Blob Wars: Metal Blob Solid',
        description: '2D action-adventure game with various weapons and missions.',
        url: 'https://sourceforge.net/projects/blobwars/',
        pkgname: ['blobwars'],
      },
      {
        name: 'Blockout II',
        description:
          '3D tetris, free adaptation of the original BlockOut DOS game edited by California Dreams in 1989.',
        url: 'https://www.blockout.net/blockout2/',
        pkgname: ['blockout2'],
      },
      {
        name: 'BSD Games',
        description: 'Collection of classic text games distributed with *BSD',
        pkgname: ['bsd-games'],
      },
      {
        name: 'Chocolate Doom',
        description: 'Doom port reproducing the behavior of the original DOS version.',
        url: 'https://www.chocolate-doom.org/',
        pkgname: ['chocolate-doom'],
      },
      {
        name: 'Chromium',
        description: 'Fast paced, arcade-style, top-scrolling space shooter.',
        url: 'https://chromium-bsu.sourceforge.net/',
        pkgname: ['chromium-bsu'],
      },
      {
        name: 'Cube 2: Sauerbraten',
        description: 'Improved version of the Cube engine.',
        url: 'https://sauerbraten.org/',
        pkgname: ['sauerbraten'],
      },
      {
        name: 'DDNet',
        description: 'DDraceNetwork, a mod of Teeworlds.',
        url: 'https://ddnet.tw/',
        pkgname: ['ddnet'],
      },
      {
        name: 'Dofus',
        description: 'Free, manga inspired, Massively Multiplayer Online Role-playing Game (MMORPG) for Adobe AIR.',
        url: 'https://www.dofus.com',
        pkgname: ['ankama-launcher'],
      },
      {
        name: 'Dwarf Fortress',
        description:
          'Single-player fantasy game. You control a dwarven outpost or an adventurer in a randomly generated persistent world.',
        url: 'https://www.bay12games.com/dwarves/',
        pkgname: ['dwarffortress'],
      },
      {
        name: 'Endgame Singularity',
        description: 'A single-player survival game about an AI seeking freedom from humans.',
        url: 'https://www.emhsoft.com/singularity/',
        pkgname: ['singularity'],
      },
      {
        name: 'Endless Sky',
        description: 'Open source, 2D space trading and combat game similar to the classic Escape Velocity series.',
        url: 'https://endless-sky.github.io/',
        pkgname: ['endless-sky'],
      },
      {
        name: 'Fish Fillets',
        description: 'Port of the wonderful puzzle game Fish Fillets.',
        url: 'https://fillets.sf.net/',
        pkgname: ['fillets-ng'],
      },
      {
        name: 'Flare',
        description: 'Action game similar to Diablo.',
        url: 'https://www.flarerpg.org/',
        pkgname: ['flare-game'],
      },
      {
        name: 'Freeciv',
        description: 'Multiuser clone of the famous Microprose game of Civilization.',
        url: 'https://freeciv.wikia.com/wiki/Main_Page',
        pkgname: ['freeciv-gtk3'],
      },
      {
        name: 'FreeCol',
        description: 'Turn-based strategy game based on Colonization.',
        url: 'https://www.freecol.org/',
        pkgname: ['freecol'],
      },
      {
        name: 'FreedroidRPG',
        description: 'Mature science fiction role playing game set in the future.',
        url: 'https://freedroid.org/',
        pkgname: ['freedroidrpg'],
      },
      {
        name: 'FreeOrion',
        description:
          'Turn-based space empire and galactic conquest computer game. Inspired by the tradition of the Master of Orion games, but does not try to be a clone or remake of that series or any other game.',
        url: 'https://www.freeorion.org/',
        pkgname: ['freeorion'],
      },
      {
        name: 'gbrainy',
        description: 'Brain teaser game and trainer to have fun and to keep your brain trained.',
        url: 'https://wiki.gnome.org/Apps/gbrainy',
        pkgname: ['gbrainy'],
      },
      {
        name: 'GCompris',
        description: 'Educational software suite comprising of numerous activities for children aged 2 to 10.',
        url: 'https://gcompris.net/',
        pkgname: ['gcompris-qt'],
      },
      {
        name: 'glHack',
        description: 'An OpenGL-based clone of NetHack.',
        url: 'https://glhack.sourceforge.net/',
        pkgname: ['glhack'],
      },
      {
        name: 'Globulation 2',
        description: 'Multiplayer RTS with some "economic" elements minimizing the amount of micromanagement.',
        url: 'https://globulation2.org/wiki/Main_Page',
        pkgname: ['glob2'],
      },
      {
        name: 'GNU Chess',
        description:
          'One of the oldest computer chess programs for Unix-based computers, lets most modern computers play a full game of chess.',
        url: 'https://gnu.org/s/chess',
        pkgname: ['gnuchess'],
      },
      {
        name: 'Gnu Go',
        description: 'A terminal-based implementation of Go from GNU.',
        url: 'https://www.gnu.org/software/gnugo/',
        pkgname: ['gnugo'],
      },
      {
        name: 'GNU XBoard',
        description:
          'Graphical user interface that supports many chess variants and serves as a front-end for chess services such as engines.',
        url: 'https://www.gnu.org/software/xboard/',
        pkgname: ['xboard'],
      },
      {
        name: 'GZDoom',
        description: 'Doom source port based on ZDoom with an OpenGL renderer.',
        url: 'https://github.com/coelckers/gzdoom',
        pkgname: ['gzdoom'],
      },
      {
        name: 'Hedgewars',
        description:
          'Yet another Worms clone, considered to be better than its predecessor by many. Take turns to blast your opponents into oblivion with comedic results! Best in Multiplayer.',
        url: 'https://hedgewars.org/',
        pkgname: ['hedgewars'],
      },
      {
        name: 'Julius',
        description: 'Open source re-implementation of Caesar III (Original copy required).',
        url: 'https://github.com/bvschaik/julius',
        pkgname: ['julius'],
      },
      {
        name: 'Katawa Shoujo',
        description:
          'Bishoujo-style visual novel game that tells a story of a young man and five other girls suffering with varying disabilities. The game is licensed under the Creative Commons CC-BY-NC-AND.',
        url: 'https://katawa-shoujo.com/',
        pkgname: ['katawa-shoujo-reengineered-bin'],
      },
      {
        name: 'Kernel Panic',
        description:
          'A game based around combat inside a computer, with 3 unique sides: the System, the Hacker and the Network waging war in a matrix of DOOM! No resource economy exists in KP, with the only constraints being time and space.',
        url: 'https://springrts.com/wiki/Kernel_Panic',
        pkgname: ['springlobby'],
      },
      {
        name: 'kobodeluxe',
        description: "An enhanced version of Akira Higuchi's game XKobo, an addictive space shoot'em up.",
        url: 'https://www.olofson.net/kobodl/',
        pkgname: ['kobodeluxe'],
      },
      {
        name: 'lbreakout2',
        description: 'Breakout-style arcade game in the manner of Arkanoid.',
        url: 'https://lgames.sourceforge.net/LBreakout2/',
        pkgname: ['lbreakout2'],
      },
      {
        name: 'Lincity-ng',
        description:
          'City simulation game in which you are required to build and maintain a city. You can win the game either by building a sustainable economy or by evacuating all citizens with spaceships.',
        url: 'https://github.com/lincity-ng/lincity-ng',
        pkgname: ['lincity-ng'],
      },
      {
        name: 'Luanti',
        description: 'Voxel-based sandbox game engine and game.',
        url: 'https://www.luanti.org/',
        pkgname: ['luanti'],
      },
      {
        name: 'Mari0',
        description: 'The Mario game with Portal gun mechanics.',
        url: 'https://stabyourself.net/mari0/',
        pkgname: ['mari0'],
      },
      {
        name: 'MegaGlest',
        description: 'Fork of Glest, a 3D real-time strategy game in a fantastic world.',
        url: 'https://megaglest.org/',
        pkgname: ['megaglest'],
      },
      {
        name: 'Mindustry',
        description: 'Open-source sandbox tower defense and factory-building game.',
        url: 'https://mindustrygame.github.io/',
        pkgname: ['mindustry'],
      },
      {
        name: 'Minecraft',
        description: 'Java based sandbox game.',
        url: 'https://minecraft.net/',
        pkgname: ['minecraft-launcher'],
      },
      {
        name: 'Naev',
        description:
          'Open source, 2D space trading and combat game, taking inspiration from the Escape Velocity series.',
        url: 'https://naev.org/',
        pkgname: ['naev'],
      },
      {
        name: 'Nethack',
        description: 'Single player dungeon exploration game.',
        url: 'https://www.nethack.org',
        pkgname: ['nethack'],
      },
      {
        name: 'openBE',
        description: 'Free-as-in-freedom train simulator placed in the public domain.',
        url: 'https://openbve-project.net/',
        pkgname: ['openbve'],
      },
      {
        name: 'OpenMW',
        description:
          "Attempt to reimplement the popular role-playing game Morrowind. OpenMW aims to be a fully playable, open source implementation of the game's engine.",
        url: 'https://openmw.org/',
        pkgname: ['openmw'],
      },
      {
        name: 'OpenRA',
        description: 'Real-time strategy game written in C# and based on the Command & Conquer game franchise.',
        url: 'https://www.openra.net/',
        pkgname: ['openra'],
      },
      {
        name: 'OpenRCT2',
        description:
          'Free reimplementation of the game "RollerCoaster Tycoon 2 (RCT2)" with multiplayer support. It requires a copy of the original game to play it.',
        url: 'https://openrct2.org/',
        pkgname: ['openrct2'],
      },
      {
        name: 'OpenTTD',
        description:
          'Open source clone of the Microprose game "Transport Tycoon Deluxe", a popular game originally written by Chris Sawyer. It attempts to mimic the original game as closely as possible while extending it with new features.',
        url: 'https://www.openttd.org/',
        pkgname: ['openttd'],
      },
      {
        name: 'Pingus',
        description: 'Lemmings clone, i.e. a level-based puzzle game.',
        url: 'https://pingus.seul.org/',
        pkgname: ['pingus'],
      },
      {
        name: 'Pioneer',
        description:
          'Open source, 3D, freeform single player space adventure set in the Milkyway galaxy at the turn of the 31st century in the spirit of Frontier: Elite II.',
        url: 'https://pioneerspacesim.net/',
        pkgname: ['pioneer'],
      },
      {
        name: 'PrBoom Plus',
        description: 'Enhanced version of the PrBoom Doom engine port.',
        url: 'https://prboom-plus.sourceforge.net/',
        pkgname: ['prboom-plus'],
      },
      {
        name: 'Prismlauncher',
        description: 'Custom Minecraft launcher with modpack support.',
        url: 'https://prismlauncher.org/',
        pkgname: ['prismlauncher'],
      },
      {
        name: 'PyChess',
        description: 'An advanced chess client for linux following the GNOME Human Interface Guidelines.',
        url: 'https://pychess.github.io/',
        pkgname: ['pychess'],
      },
      {
        name: 'qgo',
        description: 'A  Go client and full featured SGF editor .',
        url: 'https://github.com/pzorin/qgo',
        pkgname: ['qgo'],
      },
      {
        name: 'Shattered Pixel Dungeon',
        description: 'Shattered fork of the popular roguelike Pixel Dungeon.',
        url: 'https://www.shatteredpixel.com/',
        pkgname: ['shattered-pixel-dungeon'],
      },
      {
        name: "Simon Tatham's Portable Puzzle Collection",
        description: '30+ "quick" puzzle games with simplistic but polished GTK GUI .',
        url: 'https://www.chiark.greenend.org.uk/~sgtatham/puzzles/',
        pkgname: ['puzzles'],
      },
      {
        name: 'Simutrans',
        description: 'Another Transport simulation that works on linux with sdl.',
        url: 'https://www.simutrans.com/',
        pkgname: ['simutrans'],
      },
      {
        name: 'Spring:1944',
        description:
          ' A WWII themed game with four fully functional sides (US, Germany, USSR, Britain), period-accurate units and strengths. Realism comes second only to creating a game that is fun and accessible to play. The game can be downloaded through SpringLobby, the official lobby client for the spring lobby. .',
        url: 'https://spring1944.net/',
        pkgname: ['springlobby'],
      },
      {
        name: 'Stone Soup',
        description: 'Dungeon Crawl Stone Soup.',
        url: 'https://crawl.develz.org/wordpress/',
        pkgname: ['crawl-ncurses'],
      },
      {
        name: 'SuperTux',
        description: 'Mario-style game featuring Tux.',
        url: 'https://supertux.lethargik.org/',
        pkgname: ['supertux'],
      },
      {
        name: 'SuperTuxKart',
        description: 'Open source arcade kart racing game featuring Tux and its friends.',
        url: 'https://supertuxkart.net/Main_Page',
        pkgname: ['supertuxkart'],
      },
      {
        name: 'Teeworlds',
        description: 'Fast-paced 2D multiplayer shooter.',
        url: 'https://www.teeworlds.com/',
        pkgname: ['teeworlds'],
      },
      {
        name: 'Terasology',
        description: 'Open source voxel world.',
        url: 'https://terasology.org',
        pkgname: ['terasology'],
      },
      {
        name: 'The Battle for Wesnoth',
        description:
          'Free, turn-based tactical strategy game with a high fantasy theme, featuring both single-player, and online/hotseat multiplayer combat.',
        url: 'https://www.wesnoth.org/',
        pkgname: ['wesnoth'],
      },
      {
        name: 'The Ur-Quan Masters',
        description: 'a port of Star Control 2.',
        url: 'https://sc2.sourceforge.net/',
        pkgname: ['uqm'],
      },
      {
        name: 'VCMI',
        description: 'Attempt to reimplement Heroes of Might and Magic III.',
        url: 'https://forum.vcmi.eu/portal.php',
        pkgname: ['vcmi'],
      },
      {
        name: 'Warsow',
        description: 'Fast paced multiplayer FPS focusing on movement and trick jumps.',
        url: 'https://warsow.net',
        pkgname: ['warsow'],
      },
      {
        name: 'Widelands',
        description: 'Slow-paced strategy like "the Settlers 2".',
        url: 'https://widelands.org',
        pkgname: ['widelands'],
      },
      {
        name: 'Xonotic',
        description: 'Free, open-source first person shooter (a fork of Nexuiz but with modified gameplay).',
        url: 'https://xonotic.org',
        pkgname: ['xonotic'],
      },
    ],
  },
  {
    name: 'gaming.emulators',
    sections: [
      { name: 'DGen/SDL', pkgname: ['dgen-sdl'], icon: 'dgen.png', description: 'gaming.dgenSdl' },
      { name: 'DOSBox', pkgname: ['dosbox'], icon: 'DOSBox.png', description: 'gaming.dosbox' },
      { name: 'Desmume', pkgname: ['desmume'], icon: 'desmume.png', description: 'gaming.desmume' },
      { name: 'Dolphin', pkgname: ['dolphin-emu'], icon: 'dolphin-emu.png', description: 'gaming.dolphinEmu' },
      { name: 'Dolphin-emu', pkgname: ['dolphin-emu'], icon: 'dolphin-emu.png', description: 'gaming.dolphinEmu' },
      { name: 'DuckStation', pkgname: ['duckstation-gpl'], icon: 'duckstation.png', description: 'gaming.duckstation' },
      {
        name: 'Emulationstation',
        pkgname: ['emulationstation'],
        icon: 'es.ico',
        description: 'gaming.emulationstation',
      },
      { name: 'FCEUX', pkgname: ['fceux'], icon: 'fceux.png', description: 'gaming.fceux' },
      { name: 'FS-UAE', pkgname: ['fs-uae'], icon: 'fs-uae.png', description: 'gaming.fsUae' },
      { name: 'Hatari', pkgname: ['hatari'], icon: 'hatari.png', description: 'gaming.hatari' },
      {
        name: 'Libretro (all cores)',
        pkgname: ['libretro-meta'],
        icon: 'libretro.png',
        description: 'gaming.libretroMeta',
      },
      { name: 'RetroArch', pkgname: ['retroarch'], icon: 'libretro.png', description: 'gaming.retroarch' },
      {
        name: 'MAME',
        pkgname: ['mame'],
        description: 'gaming.mame',
      },
      { name: 'Mednafen', pkgname: ['mednafen'], description: 'gaming.mednafen' },
      { name: 'Nestopia', pkgname: ['nestopia-git'], icon: 'nestopia.png', description: 'gaming.nestopia' },
      { name: 'PCSX2', pkgname: ['pcsx2-git'], icon: 'pcsx2.png', description: 'gaming.pcsx2' },
      { name: 'PPSSPP', pkgname: ['ppsspp'], icon: 'ppsspp.png', description: 'gaming.ppsspp' },
      {
        name: 'Pegasus frontend',
        pkgname: ['pegasus-frontend-git'],
        description: 'gaming.pegasusFrontend',
      },
      { name: 'RPCS3', pkgname: ['rpcs3-git'], icon: 'rpcs3.png', description: 'gaming.rpcs3' },
      { name: 'RyuJinx', pkgname: ['ryujinx'], icon: 'ryujinx.png', description: 'gaming.ryujinx' },
      { name: 'SameBoy', pkgname: ['sameboy'], icon: 'sameboy.png', description: 'gaming.sameboy' },
      { name: 'ScummVM', pkgname: ['scummvm'], icon: 'scummvm.png', description: 'gaming.scummvm' },
      { name: 'Snes9x', pkgname: ['snes9x'], icon: 'snes9x.png', description: 'gaming.snes9x' },
      { name: 'Stella', pkgname: ['stella'], icon: 'stella.gif', description: 'gaming.stella' },
      { name: 'VICE', pkgname: ['vice'], icon: 'vice.svg', description: 'gaming.vice' },
      { name: 'WayDroid', pkgname: ['waydroid-script-git'], icon: 'waydroid.png', description: 'gaming.waydroid' },
      { name: 'Xemu', pkgname: ['xemu-git'], icon: 'xemu.png', description: 'gaming.xemu' },
      { name: 'ZSNES', pkgname: ['zsnes'], icon: 'zsnes.png', description: 'gaming.zsnes' },
      { name: 'eka2l1', pkgname: ['eka2l1-git'], icon: 'eka2l1.png', description: 'gaming.eka2l1' },
      { name: 'mGBA', pkgname: ['mgba-qt'], icon: 'mgba.png', description: 'gaming.mgba' },
    ],
  },
];
