packages:
  - packages/*
allowBuilds:
  '@parcel/watcher': true
  electron: true
  electron-winstaller: true
  esbuild: true
  lmdb: true
  msgpackr-extract: true
  nx: false
  unrs-resolver: true
blockExoticSubdeps: false
catalog:
  '@app/electron-versions': workspace:*
  '@app/main': workspace:*
  '@app/preload': workspace:*
  '@app/renderer': workspace:*
  typescript: ^5.9.3
  vite: ^8.0.14
minimumReleaseAgeExclude:
  - app-builder-lib@26.12.1
  - builder-util-runtime@9.6.2
  - builder-util@26.12.1
  - dmg-builder@26.12.1
  - electron-builder-squirrel-windows@26.12.1
  - electron-builder@26.12.1
  - electron-publish@26.12.1
onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - core-js
  - cpu-features
  - electron
  - esbuild
  - lmdb
  - msgpackr-extract
overrides:
  # https://github.com/electron/electron/issues/51619#issuecomment-4526580507
  yauzl: '^3.3.1'
