packages:
  - packages/*
allowBuilds:
  '@parcel/watcher': true
  electron: true
  electron-winstaller: true
  esbuild: true
  lmdb: true
  msgpackr-extract: true
  nx: false
  unrs-resolver: true
blockExoticSubdeps: false
catalog:
  '@app/electron-versions': workspace:*
  '@app/main': workspace:*
  '@app/preload': workspace:*
  '@app/renderer': workspace:*
  typescript: ^6.0.3
  vite: ^8.2.1
minimumReleaseAgeExclude:
  - '@garudalinux/core@2.0.0-rc.1'
  - '@garudalinux/themes@2.0.0-rc.1'
overrides:
  # https://github.com/electron/electron/issues/51619#issuecomment-4526580507
  yauzl: '^3.3.1'
