packages:
  - packages/*
catalog:
  '@app/electron-versions': workspace:*
  '@app/main': workspace:*
  '@app/preload': workspace:*
  '@app/renderer': workspace:*
  'typescript': ^5.9.3
  'vite': ^8.0.3
onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - core-js
  - cpu-features
  - electron
  - esbuild
  - lmdb
  - msgpackr-extract
