export const MODULE_SEARCH: ModuleSearchEntry[] = [
  {
    moduleName: 'menu.modules.appSettings',
    keywords: ['settings', 'configuration', 'preferences', 'options', 'app settings', 'application settings', 'theme'],
    routerLink: 'settings',
  },
  {
    moduleName: 'menu.modules.locales',
    keywords: [
      'locales',
      'languages',
      'translations',
      'i18n',
      'internationalization',
      'localization',
      'language packs',
    ],
    routerLink: 'system-tools',
    hash: 'locales',
  },
  {
    moduleName: 'menu.modules.kernels',
    keywords: [
      'kernels',
      'linux kernels',
      'kernel management',
      'kernel settings',
      'kernel updates',
      'lqx',
      'zen',
      'cachyos',
    ],
    routerLink: 'system-tools',
    hash: 'kernels',
  },
  {
    moduleName: 'menu.modules.diagnostics',
    keywords: [
      'diagnostics',
      'logs',
      'debugging',
      'troubleshooting',
      'error logs',
      'system logs',
      'performance',
      'monitoring',
      'journalctl',
      'journal',
      'systemd',
      'systemd-journal',
    ],
    routerLink: 'diagnostics',
  },
  {
    moduleName: 'menu.modules.systemSettings',
    keywords: [
      'system settings',
      'performance',
      'powersave',
      'rightclick emulation',
      'profile-sync-daemon',
      'psd',
      'systemd-oomd',
      'oomd',
      'guest user',
      'systemd-guest-user',
      'performance tweaks',
      'ananicy-cpp',
      'bpftune',
      'preload',
      'irqbalance',
      'powersave tweaks',
      'thermald',
      'power-profiles-daemon',
      'intel-undervolt',
      'rightclick-emulation',
      'evdev-rce',
      'evdev',
      'longpress',
      'mouse',
      'battery',
      'dns',
      'shell',
      'hblock',
      'iwd',
    ],
    routerLink: 'system-tools',
    hash: 'settings',
  },
  {
    moduleName: 'menu.modules.gaming',
    keywords: [
      'gaming',
      'games',
      'game library',
      'game management',
      'game settings',
      'game launcher',
      'gamepad',
      'controller',
      'joystick',
      'launcher',
      'steam',
      'lutris',
      'heroic',
      'proton',
      'wine',
      'dxvk',
      'vulkan',
      'gamemode',
    ],
    routerLink: 'gaming',
  },
  {
    moduleName: 'menu.modules.bootRepair',
    keywords: [
      'boot repair',
      'grub repair',
      'grub reinstall',
      'bootloader repair',
      'bootloader reinstall',
      'mbr',
      'pbr',
      'esp',
      'luks',
      'cryptsetup',
    ],
    routerLink: 'boot-repair',
  },
  {
    moduleName: 'menu.modules.components',
    keywords: [
      'audio',
      'virtualization',
      'containers',
      'network',
      'bluetooth',
      'printing',
      'scanning',
      'firewall',
      'pipewire',
      'alsa',
      'jack',
      'pulseaudio',
      'realtime',
      'easyeffects',
      'lsp-plugins',
      'calf',
      'jamesdsp',
      'virt-manager',
      'libvirt',
      'libvirtd',
      'kvm',
      'qemu',
      'virtualbox',
      'qemu-user-static',
      'binfmt',
      'docker',
      'docker-compose',
      'podman',
      'podman-desktop',
      'distrobox',
      'boxbuddy',
      'winboat',
      'networkmanager',
      'modemmanager',
      'cups',
      'saned',
      'ufw',
      'firewalld',
      'opensnitch',
      'garuda-nix-subsystem',
    ],
    routerLink: 'system-tools',
    hash: 'components',
  },
  {
    moduleName: 'menu.modules.maintenance',
    keywords: [
      'skel',
      'config',
      'reset',
      'btrfs',
      'default',
      'lock',
      'repository',
      'garuda-update',
      'reinstall',
      'pacman',
      'reflector-simple',
      'btrfs-assistant',
      'mirrors',
      'orphans',
      'cache',
      'system',
      'update',
      'clean',
      'refresh',
      'merge',
      'pacdiff',
    ],
    routerLink: 'maintenance',
  },
  {
    moduleName: 'menu.modules.welcome',
    keywords: [
      'help',
      'support',
      'documentation',
      'guides',
      'assistance',
      'contact',
      'forum',
      'community',
      'tutorials',
    ],
    routerLink: '',
  },
  {
    moduleName: 'menu.modules.packages',
    keywords: ['packages', 'software', 'applications', 'installed packages', 'package manager'],
    routerLink: 'system-tools',
    hash: 'packages',
  },
  {
    moduleName: 'menu.modules.systemdServices',
    keywords: [
      'systemd services',
      'services',
      'daemons',
      'system services',
      'service management',
      'systemctl',
      'restart',
      'enable',
      'disable',
    ],
    routerLink: 'system-tools',
    hash: 'services',
  },
  {
    moduleName: 'menu.configFiles',
    keywords: [
      'config',
      'settings',
      'configuration',
      'files',
      'pacman.conf',
      'makepkg.conf',
      'fstab',
      'environment',
      'grub',
      'vconsole.conf',
      'locale.conf',
      'hostname',
      'hosts',
      'bashrc',
      'zshrc',
      'fish',
      'starship',
    ],
    routerLink: 'config-files',
  },
];

export interface ModuleSearchEntry {
  moduleName: string;
  keywords: string[];
  routerLink: string;
  hash?: string;
}
