export type Locales = Record<
  string,
  {
    name: string;
    native: string;
    flag: string;
  }
>;

export const locales: Locales = {
  aa: { name: 'Afar', native: 'Afar', flag: '🇩🇯' },
  ab: { name: 'Abkhazian', native: 'Аҧсуа', flag: '🇦🇧' },
  af: { name: 'Afrikaans', native: 'Afrikaans', flag: '🇿🇦' },
  ak: { name: 'Akan', native: 'Akana', flag: '🇬🇭' },
  am: { name: 'Amharic', native: 'አማርኛ', flag: '🇪🇹' },
  an: { name: 'Aragonese', native: 'Aragonés', flag: '🇪🇸' },
  ar: { name: 'Arabic', native: 'العربية', flag: '🇦🇪' },
  as: { name: 'Assamese', native: 'অসমীয়া', flag: '🇮🇳' },
  av: { name: 'Avar', native: 'Авар', flag: '🇷🇺' },
  ay: { name: 'Aymara', native: 'Aymar', flag: '🇧🇴' },
  az: { name: 'Azerbaijani', native: 'Azərbaycanca / آذربايجان', flag: '🇦🇿' },
  ba: { name: 'Bashkir', native: 'Башҡорт', flag: '🇷🇺' },
  be: { name: 'Belarusian', native: 'Беларуская', flag: '🇧🇾' },
  bg: { name: 'Bulgarian', native: 'Български', flag: '🇧🇬' },
  bh: { name: 'Bihari', native: 'भोजपुरी', flag: '🇮🇳' },
  bi: { name: 'Bislama', native: 'Bislama', flag: '🇻🇺' },
  bm: { name: 'Bambara', native: 'Bamanankan', flag: '���🇱' },
  bn: { name: 'Bengali', native: 'বাংলা', flag: '🇧🇩' },
  bo: { name: 'Tibetan', native: 'བོད་ཡིག / Bod skad', flag: '🇨🇳' },
  br: { name: 'Breton', native: 'Brezhoneg', flag: '🇫🇷' },
  bs: { name: 'Bosnian', native: 'Bosanski', flag: '🇧🇦' },
  ca: { name: 'Catalan', native: 'Català', flag: '🇪🇸' },
  ce: { name: 'Chechen', native: 'Нохчийн', flag: '🇷🇺' },
  ch: { name: 'Chamorro', native: 'Chamoru', flag: '🇬🇺' },
  co: { name: 'Corsican', native: 'Corsu', flag: '🇫🇷' },
  cr: { name: 'Cree', native: 'Nehiyaw', flag: '🇨🇦' },
  cs: { name: 'Czech', native: 'Česky', flag: '🇨🇿' },
  cu: {
    name: 'Old Church Slavonic / Old Bulgarian',
    native: 'словѣньскъ / slověnĭskŭ',
    flag: '🇧🇬',
  },
  cv: { name: 'Chuvash', native: 'Чăваш', flag: '🇷🇺' },
  cy: { name: 'Welsh', native: 'Cymraeg', flag: '🇬🇧' },
  da: { name: 'Danish', native: 'Dansk', flag: '🇩🇰' },
  de: { name: 'German', native: 'Deutsch', flag: '🇩🇪' },
  dv: { name: 'Divehi', native: 'ދިވެހިބަސް', flag: '🇲🇻' },
  dz: { name: 'Dzongkha', native: 'ཇོང་ཁ', flag: '🇧🇹' },
  ee: { name: 'Ewe', native: 'Ɛʋɛ', flag: '🇬🇭' },
  el: { name: 'Greek', native: 'Ελληνικά', flag: '🇬🇷' },
  en: { name: 'English', native: 'English', flag: '🇬🇧' },
  eo: { name: 'Esperanto', native: 'Esperanto', flag: '🏳️' },
  es: { name: 'Spanish', native: 'Español', flag: '🇪🇸' },
  et: { name: 'Estonian', native: 'Eesti', flag: '🇪🇪' },
  eu: { name: 'Basque', native: 'Euskara', flag: '🇪🇸' },
  fa: { name: 'Persian', native: 'فارسی', flag: '🇮🇷' },
  ff: { name: 'Peul', native: 'Fulfulde', flag: '🇸🇳' },
  fi: { name: 'Finnish', native: 'Suomi', flag: '🇫🇮' },
  fj: { name: 'Fijian', native: 'Na Vosa Vakaviti', flag: '🇫🇯' },
  fo: { name: 'Faroese', native: 'Føroyskt', flag: '🇫🇴' },
  fr: { name: 'French', native: 'Français', flag: '🇫🇷' },
  fy: { name: 'West Frisian', native: 'Frysk', flag: '🇳🇱' },
  ga: { name: 'Irish', native: 'Gaeilge', flag: '🇮🇪' },
  gd: { name: 'Scottish Gaelic', native: 'Gàidhlig', flag: '🏴' },
  gl: { name: 'Galician', native: 'Galego', flag: '🇪🇸' },
  gn: { name: 'Guatoolbox', native: "Avañe'ẽ", flag: '🇵🇾' },
  gu: { name: 'Gujarati', native: 'ગુજરાતી', flag: '🇮🇳' },
  gv: { name: 'Manx', native: 'Gaelg', flag: '🇮🇲' },
  ha: { name: 'Hausa', native: 'هَوُسَ', flag: '🇳🇬' },
  he: { name: 'Hebrew', native: 'עברית', flag: '🇮🇱' },
  hi: { name: 'Hindi', native: 'हिन्दी', flag: '🇮🇳' },
  ho: { name: 'Hiri Motu', native: 'Hiri Motu', flag: '🇵🇬' },
  hr: { name: 'Croatian', native: 'Hrvatski', flag: '🇭🇷' },
  ht: { name: 'Haitian', native: 'Krèyol ayisyen', flag: '🇭🇹' },
  hu: { name: 'Hungarian', native: 'Magyar', flag: '🇭🇺' },
  hy: { name: 'Armenian', native: 'Հայերեն', flag: '🇦🇲' },
  hz: { name: 'Herero', native: 'Otsiherero', flag: '🇳🇦' },
  ia: { name: 'Interlingua', native: 'Interlingua', flag: '🏳️' },
  id: { name: 'Indonesian', native: 'Bahasa Indonesia', flag: '🇮🇩' },
  ie: { name: 'Interlingue', native: 'Interlingue', flag: '🏳️' },
  ig: { name: 'Igbo', native: 'Igbo', flag: '🇳🇬' },
  ii: { name: 'Sichuan Yi', native: 'ꆇꉙ / 四川彝语', flag: '🇨🇳' },
  ik: { name: 'Inupiak', native: 'Iñupiak', flag: '🇺🇸' },
  io: { name: 'Ido', native: 'Ido', flag: '🏳️' },
  is: { name: 'Icelandic', native: 'Íslenska', flag: '🇮🇸' },
  it: { name: 'Italian', native: 'Italiano', flag: '🇮🇹' },
  iu: { name: 'Inuktitut', native: 'ᐃᓄᒃᑎᑐᑦ', flag: '🇨🇦' },
  ja: { name: 'Japanese', native: '日本語', flag: '🇯🇵' },
  jv: { name: 'Javanese', native: 'Basa Jawa', flag: '🇮🇩' },
  ka: { name: 'Georgian', native: '���ართული', flag: '🇬🇪' },
  kg: { name: 'Kongo', native: 'KiKongo', flag: '🇨🇩' },
  ki: { name: 'Kikuyu', native: 'Gĩkũyũ', flag: '🇰🇪' },
  kj: { name: 'Kuanyama', native: 'Kuanyama', flag: '🇳🇦' },
  kk: { name: 'Kazakh', native: 'Қазақша', flag: '🇰🇿' },
  kl: { name: 'Greenlandic', native: 'Kalaallisut', flag: '🇬🇱' },
  km: { name: 'Cambodian', native: 'ភាសាខ្មែរ', flag: '🇰🇭' },
  kn: { name: 'Kannada', native: 'ಕನ್ನಡ', flag: '🇮🇳' },
  ko: { name: 'Korean', native: '한국어', flag: '🇰🇷' },
  kr: { name: 'Kanuri', native: 'Kanuri', flag: '🇳🇬' },
  ks: { name: 'Kashmiri', native: 'कश्मीरी / كشميري', flag: '🇮🇳' },
  ku: { name: 'Kurdish', native: 'Kurdî / كوردی', flag: '🇹🇷' },
  kv: { name: 'Komi', native: 'Коми', flag: '🇷🇺' },
  kw: { name: 'Cornish', native: 'Kernewek', flag: '🏴' },
  ky: { name: 'Kirghiz', native: 'Kırgızca / Кыргызча', flag: '🇰🇬' },
  la: { name: 'Latin', native: 'Latina', flag: '🇻🇦' },
  lb: { name: 'Luxembourgish', native: 'Lëtzebuergesch', flag: '🇱🇺' },
  lg: { name: 'Ganda', native: 'Luganda', flag: '🇺🇬' },
  li: { name: 'Limburgian', native: 'Limburgs', flag: '🇳🇱' },
  ln: { name: 'Lingala', native: 'Lingála', flag: '🇨🇩' },
  lo: { name: 'Laotian', native: 'ລາວ / Pha xa lao', flag: '🇱🇦' },
  lt: { name: 'Lithuanian', native: 'Lietuvių', flag: '🇱🇹' },
  lv: { name: 'Latvian', native: 'Latviešu', flag: '🇱🇻' },
  mg: { name: 'Malagasy', native: 'Malagasy', flag: '🇲🇬' },
  mh: { name: 'Marshallese', native: 'Kajin Majel / Ebon', flag: '🇲🇭' },
  mi: { name: 'Maori', native: 'Māori', flag: '🇳🇿' },
  mk: { name: 'Macedonian', native: 'Македонски', flag: '🇲🇰' },
  ml: { name: 'Malayalam', native: 'മലയാളം', flag: '🇮🇳' },
  mn: { name: 'Mongolian', native: 'Монгол', flag: '🇲🇳' },
  mo: { name: 'Moldovan', native: 'Moldovenească', flag: '🇲🇩' },
  mr: { name: 'Marathi', native: 'मराठी', flag: '🇮🇳' },
  ms: { name: 'Malay', native: 'Bahasa Melayu', flag: '🇲🇾' },
  mt: { name: 'Maltese', native: 'bil-Malti', flag: '🇲🇹' },
  my: { name: 'Burmese', native: 'Myanmasa', flag: '🇲🇲' },
  na: { name: 'Nauruan', native: 'Dorerin Naoero', flag: '🇳🇷' },
  and: { name: 'North Ndebele', native: 'Sindebele', flag: '🇿🇼' },
  ne: { name: 'Nepali', native: 'नेपाली', flag: '🇳🇵' },
  ng: { name: 'Ndonga', native: 'Oshiwambo', flag: '🇳🇦' },
  nl: { name: 'Dutch', native: 'Nederlands', flag: '🇳🇱' },
  nn: { name: 'Norwegian Nynorsk', native: 'Norsk (nynorsk)', flag: '🇳🇴' },
  no: { name: 'Norwegian', native: 'Norsk (bokmål / riksmål)', flag: '🇳🇴' },
  nr: { name: 'South Ndebele', native: 'isiNdebele', flag: '🇿🇼' },
  nv: { name: 'Navajo', native: 'Diné bizaad', flag: '🇺🇸' },
  ny: { name: 'Chichewa', native: 'Chi-Chewa', flag: '🇲🇼' },
  oc: { name: 'Occitan', native: 'Occitan', flag: '🇫🇷' },
  oj: { name: 'Ojibwa', native: 'ᐊᓂᔑᓈᐯᒧᐎᓐ / Anishinaabemowin', flag: '🇨🇦' },
  om: { name: 'Oromo', native: 'Oromoo', flag: '🇪🇹' },
  or: { name: 'Oriya', native: 'ଓଡ଼ିଆ', flag: '🇮🇳' },
  os: { name: 'Ossetian / Ossetic', native: 'Иронау', flag: '🇷🇺' },
  pi: { name: 'Pali', native: 'Pāli / पाऴि', flag: '🏳️' },
  pl: { name: 'Polish', native: 'Polski', flag: '🇵🇱' },
  ps: { name: 'Pashto', native: 'پښتو', flag: '🇦🇫' },
  pt: { name: 'Portuguese', native: 'Português', flag: '🇵🇹' },
  qu: { name: 'Quechua', native: 'Runa Simi', flag: '🇵🇪' },
  rm: { name: 'Raeto Romance', native: 'Rumantsch', flag: '🇨🇭' },
  rn: { name: 'Kirundi', native: 'Kirundi', flag: '🇧🇮' },
  ro: { name: 'Romanian', native: 'Română', flag: '🇷🇴' },
  ru: { name: 'Russian', native: 'Русский', flag: '🇷🇺' },
  rw: { name: 'Rwandi', native: 'Kinyarwandi', flag: '🇷🇼' },
  sa: { name: 'Sanskrit', native: 'संस्कृतम्', flag: '🇮🇳' },
  sc: { name: 'Sardinian', native: 'Sardu', flag: '🇮🇹' },
  sd: { name: 'Sindhi', native: 'सिनधि', flag: '��🇰' },
  se: { name: 'Northern Sami', native: 'Davvisámegiella', flag: '🇸🇪' },
  sg: { name: 'Sango', native: 'Sängö', flag: '🇨🇫' },
  sh: {
    name: 'Serbo-Croatian',
    native: 'Srpskohrvatski / Српскохрватски',
    flag: '🇷🇸',
  },
  si: { name: 'Sinhalese', native: 'සිංහල', flag: '🇱🇰' },
  sk: { name: 'Slovak', native: 'Slovenčina', flag: '🇸🇰' },
  sl: { name: 'Slovenian', native: 'Slovenščina', flag: '🇸🇮' },
  sm: { name: 'Samoan', native: 'Gagana Samoa', flag: '🇼🇸' },
  sn: { name: 'Shona', native: 'chiShona', flag: '🇿🇼' },
  so: { name: 'Somalia', native: 'Soomaaliga', flag: '🇸🇴' },
  sq: { name: 'Albanian', native: 'Shqip', flag: '🇦🇱' },
  sr: { name: 'Serbian', native: 'Српски', flag: '🇷🇸' },
  ss: { name: 'Swati', native: 'SiSwati', flag: '🇸🇿' },
  st: { name: 'Southern Sotho', native: 'Sesotho', flag: '🇱🇸' },
  su: { name: 'Sundanese', native: 'Basa Sunda', flag: '🇮🇩' },
  sv: { name: 'Swedish', native: 'Svenska', flag: '🇸🇪' },
  sw: { name: 'Swahili', native: 'Kiswahili', flag: '🇹🇿' },
  ta: { name: 'Tamil', native: 'தமிழ்', flag: '🇮🇳' },
  te: { name: 'Telugu', native: 'తెలుగు', flag: '🇮🇳' },
  tg: { name: 'Tajik', native: 'Тоҷикӣ', flag: '🇹🇯' },
  th: { name: 'Thai', native: 'ไทย / Phasa Thai', flag: '🇹🇭' },
  ti: { name: 'Tigrinya', native: 'ትግርኛ', flag: '🇪🇷' },
  tk: { name: 'Turkmen', native: 'Туркмен / تركمن', flag: '🇹🇲' },
  tl: { name: 'Tagalog', native: 'Tagalog', flag: '🇵🇭' },
  tn: { name: 'Tswana', native: 'Setswana', flag: '🇧🇼' },
  to: { name: 'Tonga', native: 'Lea Faka-Tonga', flag: '🇹🇴' },
  tr: { name: 'Turkish', native: 'Türkçe', flag: '🇹🇷' },
  ts: { name: 'Tsonga', native: 'Xitsonga', flag: '🇿🇦' },
  tt: { name: 'Tatar', native: 'Tatarça', flag: '🇷🇺' },
  tw: { name: 'Twi', native: 'Twi', flag: '🇬🇭' },
  ty: { name: 'Tahitian', native: 'Reo Mā`ohi', flag: '🇵🇫' },
  ug: { name: 'Uyghur', native: 'Uyƣurqə / ئۇيغۇرچە', flag: '🇨🇳' },
  uk: { name: 'Ukrainian', native: 'Українська', flag: '🇺🇦' },
  ur: { name: 'Urdu', native: 'اردو', flag: '🇵🇰' },
  uz: { name: 'Uzbek', native: 'Ўзбек', flag: '🇺🇿' },
  ve: { name: 'Venda', native: 'Tshivenḓa', flag: '🇿🇦' },
  vi: { name: 'Vietnamese', native: 'Việtnam', flag: '🇻🇳' },
  vo: { name: 'Volapük', native: 'Volapük', flag: '🏳️' },
  wa: { name: 'Walloon', native: 'Walon', flag: '🇧🇪' },
  wo: { name: 'Wolof', native: 'Wollof', flag: '🇸🇳' },
  xh: { name: 'Xhosa', native: 'isiXhosa', flag: '🇿🇦' },
  yi: { name: 'Yiddish', native: 'ייִדיש', flag: '🇮🇱' },
  yo: { name: 'Yoruba', native: 'Yorùbá', flag: '🇳🇬' },
  za: { name: 'Zhuang', native: 'Cuengh / Tôô / 壮语', flag: '🇨🇳' },
  zh: { name: 'Chinese', native: '中文', flag: '🇨🇳' },
  zu: { name: 'Zulu', native: 'isiZulu', flag: '🇿🇦' },
  nb: { name: 'Norwegian Bokmål', native: 'Norsk (bokmål)', flag: '🇳🇴' },
};

export const localeMap = new Map<string, string>([
  ['de_DE', 'German 🇩🇪'],
  ['af_ZA', 'Afrikaans 🇿🇦'],
  ['an_ES', 'Aragonese 🇪🇸'],
  ['ar_AE', 'Arabic 🇦🇪'],
  ['ar_BH', 'Arabic 🇧🇭'],
  ['ar_DZ', 'Arabic 🇩🇿'],
  ['ar_IQ', 'Arabic 🇮🇶'],
  ['ar_JO', 'Arabic 🇯🇴'],
  ['ar_KW', 'Arabic 🇰🇼'],
  ['ar_LB', 'Arabic 🇱🇧'],
  ['ar_LY', 'Arabic 🇱🇾'],
  ['ar_MA', 'Arabic 🇲🇦'],
  ['ar_OM', 'Arabic 🇴🇲'],
  ['ar_QA', 'Arabic 🇶🇦'],
  ['ar_SA', 'Arabic 🇸🇦'],
  ['ar_SD', 'Arabic 🇸🇩'],
  ['ar_SY', 'Arabic 🇸🇾'],
  ['ar_TN', 'Arabic 🇹🇳'],
  ['ar_YE', 'Arabic 🇾🇪'],
  ['ast_ES', 'Asturian 🇪🇸'],
  ['be_BY', 'Belarusian 🇧🇾'],
  ['bg_BG', 'Bulgarian 🇧🇬'],
  ['bs_BA', 'Bosnian 🇧🇦'],
  ['ca_AD', 'Catalan 🇦🇩'],
  ['ca_ES', 'Catalan 🇪🇸'],
  ['ca_FR', 'Catalan 🇫🇷'],
  ['ca_IT', 'Catalan 🇮🇹'],
  ['cs_CZ', 'Czech 🇨🇿'],
  ['cy_GB', 'Welsh 🇬🇧'],
  ['da_DK', 'Danish 🇩🇰'],
  ['de_AT', 'German 🇦🇹'],
  ['de_BE', 'German 🇧🇪'],
  ['de_CH', 'German 🇨🇭'],
  ['de_IT', 'German 🇮🇹'],
  ['de_LI', 'German 🇱🇮'],
  ['de_LU', 'German 🇱🇺'],
  ['el_GR', 'Greek 🇬🇷'],
  ['en_AU', 'English 🇦🇺'],
  ['en_BW', 'English 🇧🇼'],
  ['en_CA', 'English 🇨🇦'],
  ['en_DK', 'English 🇩🇰'],
  ['en_GB', 'English 🇬🇧'],
  ['en_HK', 'English 🇭🇰'],
  ['en_IN', 'English 🇮🇳'],
  ['en_NZ', 'English 🇳🇿'],
  ['en_PH', 'English 🇵🇭'],
  ['en_SG', 'English 🇸🇬'],
  ['en_US', 'English 🇺🇸'],
  ['en_ZA', 'English 🇿🇦'],
  ['es_AR', 'Spanish 🇦🇷'],
  ['es_CL', 'Spanish 🇨🇱'],
  ['es_CO', 'Spanish 🇨🇴'],
  ['es_CR', 'Spanish 🇨🇷'],
  ['es_DO', 'Spanish 🇩🇴'],
  ['es_EC', 'Spanish 🇪🇨'],
  ['es_ES', 'Spanish 🇪🇸'],
  ['es_GT', 'Spanish 🇬🇹'],
  ['es_HN', 'Spanish 🇭🇳'],
  ['es_MX', 'Spanish 🇲🇽'],
  ['es_NI', 'Spanish 🇳🇮'],
  ['es_PA', 'Spanish 🇵🇦'],
  ['es_PE', 'Spanish 🇵🇪'],
  ['es_PR', 'Spanish 🇵🇷'],
  ['es_PY', 'Spanish 🇵🇾'],
  ['es_SV', 'Spanish 🇸🇻'],
  ['es_US', 'Spanish 🇺🇸'],
  ['es_UY', 'Spanish 🇺🇾'],
  ['es_VE', 'Spanish 🇻🇪'],
  ['et_EE', 'Estonian 🇪🇪'],
  ['fi_FI', 'Finnish 🇫🇮'],
  ['fr_BE', 'French 🇧🇪'],
  ['fr_CA', 'French 🇨🇦'],
  ['fr_CH', 'French 🇨🇭'],
  ['fr_FR', 'French 🇫🇷'],
  ['fr_LU', 'French 🇱🇺'],
  ['ga_IE', 'Irish 🇮🇪'],
  ['gl_ES', 'Galician 🇪🇸'],
  ['he_IL', 'Hebrew 🇮🇱'],
  ['hr_HR', 'Croatian 🇭🇷'],
  ['hu_HU', 'Hungarian 🇭🇺'],
  ['id_ID', 'Indonesian 🇮🇩'],
  ['is_IS', 'Icelandic 🇮🇸'],
  ['it_CH', 'Italian 🇨🇭'],
  ['it_IT', 'Italian 🇮🇹'],
  ['ja_JP', 'Japanese 🇯🇵'],
  ['ko_KR', 'Korean 🇰🇷'],
  ['lt_LT', 'Lithuanian 🇱🇹'],
  ['lv_LV', 'Latvian 🇱🇻'],
  ['nb_NO', 'Norwegian 🇳🇴'],
  ['nl_BE', 'Dutch 🇧🇪'],
  ['nl_NL', 'Dutch 🇳🇱'],
  ['nn_NO', 'Norwegian 🇳🇴'],
  ['pl_PL', 'Polish 🇵🇱'],
  ['pt_BR', 'Portuguese 🇧🇷'],
  ['pt_PT', 'Portuguese 🇵🇹'],
  ['ro_RO', 'Romanian 🇷🇴'],
  ['ru_RU', 'Russian 🇷🇺'],
  ['sk_SK', 'Slovak 🇸🇰'],
  ['sl_SI', 'Slovenian 🇸🇮'],
  ['sr_RS', 'Serbian 🇷🇸'],
  ['sv_FI', 'Swedish 🇫🇮'],
  ['sv_SE', 'Swedish 🇸🇪'],
  ['tr_TR', 'Turkish 🇹🇷'],
  ['uk_UA', 'Ukrainian 🇺🇦'],
  ['vi_VN', 'Vietnamese 🇻🇳'],
  ['zh_CN', 'Chinese 🇨🇳'],
  ['zh_TW', 'Chinese 🇹🇼'],
]);
