import { SetupSoftwareCategory } from './interfaces';

export const setupWizardData: SetupSoftwareCategory[] = [
  {
    id: 'audio',
    name: 'setupWizard.autoCategories.audio',
    items: [
      {
        id: 'strawberryPlayer',
        name: 'Strawberry Player',
        description: 'setupWizard.autoSoftware.strawberryPlayer',
        packages: ['strawberry'],
        selected: false,
      },
      {
        id: 'lollypop',
        name: 'Lollypop',
        description: 'setupWizard.autoSoftware.lollypop',
        packages: ['lollypop'],
        selected: false,
      },
      {
        id: 'audacious',
        name: 'Audacious',
        description: 'setupWizard.autoSoftware.audacious',
        packages: ['audacious'],
        selected: false,
      },
      {
        id: 'elisa',
        name: 'Elisa',
        description: 'setupWizard.autoSoftware.elisa',
        packages: ['elisa'],
        selected: false,
      },
      {
        id: 'kwave',
        name: 'Kwave',
        description: 'setupWizard.autoSoftware.kwave',
        packages: ['kwave'],
        selected: false,
      },
      {
        id: 'audacity',
        name: 'Audacity',
        description: 'setupWizard.autoSoftware.audacity',
        packages: ['audacity'],
        selected: false,
      },
      {
        id: 'ardour',
        name: 'Ardour',
        description: 'setupWizard.autoSoftware.ardour',
        packages: ['ardour'],
        selected: false,
      },
      {
        id: 'lmms',
        name: 'LMMS',
        description: 'setupWizard.autoSoftware.lmms',
        packages: ['lmms'],
        selected: false,
      },
      {
        id: 'mixxx',
        name: 'Mixxx',
        description: 'setupWizard.autoSoftware.mixxx',
        packages: ['mixxx'],
        selected: false,
      },
      {
        id: 'museScore',
        name: 'MuseScore',
        description: 'setupWizard.autoSoftware.museScore',
        packages: ['musescore'],
        selected: false,
      },
      {
        id: 'rosegarden',
        name: 'Rosegarden',
        description: 'setupWizard.autoSoftware.rosegarden',
        packages: ['rosegarden'],
        selected: false,
      },
      {
        id: 'bitwigStudio',
        name: 'Bitwig Studio',
        description: 'setupWizard.autoSoftware.bitwigStudio',
        packages: ['bitwig-studio'],
        selected: false,
      },
    ],
  },
  {
    id: 'browsers',
    name: 'setupWizard.autoCategories.browsers',
    items: [
      {
        id: 'firedragon',
        name: 'Firedragon',
        description: 'setupWizard.autoSoftware.firedragon',
        packages: ['firedragon'],
        selected: false,
      },
      {
        id: 'firedragonCatppuccin',
        name: 'Firedragon Catppuccin',
        description: 'setupWizard.autoSoftware.firedragonCatppuccin',
        packages: ['firedragon-catppuccin'],
        selected: false,
        icon: 'firedragon',
      },
      {
        id: 'librewolf',
        name: 'Librewolf',
        description: 'setupWizard.autoSoftware.librewolf',
        packages: ['librewolf'],
        selected: false,
      },
      {
        id: 'firefox',
        name: 'Firefox',
        description: 'setupWizard.autoSoftware.firefox',
        packages: ['firefox'],
        selected: false,
      },
      {
        id: 'firefoxEsr',
        name: 'Firefox ESR',
        description: 'setupWizard.autoSoftware.firefoxEsr',
        packages: ['firefox-esr'],
        selected: false,
      },
      {
        id: 'chromium',
        name: 'Chromium',
        description: 'setupWizard.autoSoftware.chromium',
        packages: ['chromium'],
        selected: false,
      },
      {
        id: 'ungoogledChromium',
        name: 'Ungoogled Chromium',
        description: 'setupWizard.autoSoftware.ungoogledChromium',
        packages: ['ungoogled-chromium-bin'],
        selected: false,
      },
      {
        id: 'vivaldi',
        name: 'Vivaldi',
        description: 'setupWizard.autoSoftware.vivaldi',
        packages: ['vivaldi', 'vivaldi-ffmpeg-codecs'],
        selected: false,
      },
      {
        id: 'torBrowser',
        name: 'Tor Browser',
        description: 'setupWizard.autoSoftware.torBrowser',
        packages: ['torbrowser-launcher'],
        selected: false,
        icon: 'tor-browser',
      },
      {
        id: 'brave',
        name: 'Brave',
        description: 'setupWizard.autoSoftware.brave',
        packages: ['brave-bin'],
        selected: false,
      },
      {
        id: 'falkon',
        name: 'Falkon',
        description: 'setupWizard.autoSoftware.falkon',
        packages: ['falkon'],
        selected: false,
      },
      {
        id: 'qutebrowser',
        name: 'Qutebrowser',
        description: 'setupWizard.autoSoftware.qutebrowser',
        packages: ['qutebrowser', 'python-adblock'],
        selected: false,
      },
    ],
  },
  {
    id: 'communication',
    name: 'setupWizard.autoCategories.communication',
    items: [
      {
        id: 'telegram',
        name: 'Telegram',
        description: 'setupWizard.autoSoftware.telegram',
        packages: ['telegram-desktop'],
        selected: false,
      },
      {
        id: 'discord',
        name: 'Discord',
        description: 'setupWizard.autoSoftware.discord',
        packages: ['discord'],
        selected: false,
      },
      {
        id: 'neochat',
        name: 'Neochat',
        description: 'setupWizard.autoSoftware.neochat',
        packages: ['neochat'],
        selected: false,
      },
      {
        id: 'fractal',
        name: 'Fractal',
        description: 'setupWizard.autoSoftware.fractal',
        packages: ['fractal'],
        selected: false,
      },
      {
        id: 'element',
        name: 'Element',
        description: 'setupWizard.autoSoftware.element',
        packages: ['element-desktop'],
        selected: false,
      },
      {
        id: 'wire',
        name: 'Wire',
        description: 'setupWizard.autoSoftware.wire',
        packages: ['wire-desktop'],
        selected: false,
      },
      {
        id: 'signal',
        name: 'Signal',
        description: 'setupWizard.autoSoftware.signal',
        packages: ['signal-desktop'],
        selected: false,
      },
      {
        id: 'jitsiMeet',
        name: 'Jitsi-Meet',
        description: 'setupWizard.autoSoftware.jitsiMeet',
        packages: ['jitsi-meet-desktop'],
        selected: false,
      },
      {
        id: 'zoom',
        name: 'Zoom',
        description: 'setupWizard.autoSoftware.zoom',
        packages: ['zoom'],
        selected: false,
      },
      {
        id: 'microsoftTeams',
        name: 'Microsoft Teams',
        description: 'setupWizard.autoSoftware.microsoftTeams',
        packages: ['teams-for-linux'],
        selected: false,
      },
      {
        id: 'slack',
        name: 'Slack',
        description: 'setupWizard.autoSoftware.slack',
        packages: ['slack-desktop'],
        selected: false,
      },
      {
        id: 'mumble',
        name: 'Mumble',
        description: 'setupWizard.autoSoftware.mumble',
        packages: ['mumble'],
        selected: false,
      },
      {
        id: 'twitchGui',
        name: 'Twitch GUI',
        description: 'setupWizard.autoSoftware.twitchGui',
        packages: ['streamlink-twitch-gui-bin'],
        selected: false,
      },
    ],
  },
  {
    id: 'development',
    name: 'setupWizard.autoCategories.development',
    items: [
      {
        id: 'vim',
        name: 'VIM',
        description: 'setupWizard.autoSoftware.vim',
        packages: ['vim'],
        selected: false,
      },
      {
        id: 'visualStudioCode',
        name: 'Visual Studio Code',
        description: 'setupWizard.autoSoftware.visualStudioCode',
        packages: ['visual-studio-code-bin'],
        selected: false,
      },
      {
        id: 'visualStudioCodeOss',
        name: 'Visual Studio Code',
        description: 'setupWizard.autoSoftware.visualStudioCodeOss',
        packages: ['code'],
        selected: false,
      },
      {
        id: 'zedEditor',
        name: 'Zed Editor',
        description: 'setupWizard.autoSoftware.zedEditor',
        packages: ['zed'],
        selected: false,
      },
      {
        id: 'vscodium',
        name: 'VSCodium',
        description: 'setupWizard.autoSoftware.vscodium',
        packages: ['vscodium'],
        selected: false,
      },
      {
        id: 'gnu',
        name: 'GNU',
        description: 'setupWizard.autoSoftware.gnu',
        packages: ['emacs'],
        selected: false,
      },
      {
        id: 'qtCreator',
        name: 'QtCreator',
        description: 'setupWizard.autoSoftware.qtCreator',
        packages: ['qtcreator'],
        selected: false,
      },
      {
        id: 'gnomeBuilder',
        name: 'GNOME Builder',
        description: 'setupWizard.autoSoftware.gnomeBuilder',
        packages: ['gnome-builder'],
        selected: false,
      },
      {
        id: 'kDevelop',
        name: 'KDevelop',
        description: 'setupWizard.autoSoftware.kDevelop',
        packages: ['kdevelop'],
        selected: false,
      },
      {
        id: 'netbeans',
        name: 'Netbeans',
        description: 'setupWizard.autoSoftware.netbeans',
        packages: ['netbeans'],
        selected: false,
      },
      {
        id: 'postman',
        name: 'Postman',
        description: 'setupWizard.autoSoftware.postman',
        packages: ['postman-bin'],
        selected: false,
      },
      {
        id: 'intellijIdea',
        name: 'IntelliJ-IDEA',
        description: 'setupWizard.autoSoftware.intellijIdea',
        packages: ['intellij-idea-community-edition'],
        selected: false,
      },
      {
        id: 'pyCharm',
        name: 'PyCharm',
        description: 'setupWizard.autoSoftware.pyCharm',
        packages: ['pycharm-community-edition'],
        selected: false,
      },
      {
        id: 'gitKraken',
        name: 'Gitkraken',
        description: 'setupWizard.autoSoftware.gitKraken',
        packages: ['gitkraken'],
        selected: false,
      },
      {
        id: 'github',
        name: 'GitHub',
        description: 'setupWizard.autoSoftware.github',
        packages: ['github-desktop'],
        selected: false,
      },
      {
        id: 'cockpit',
        name: 'Cockpit',
        description: 'setupWizard.autoSoftware.cockpit',
        packages: ['cockpit', 'cockpit-machines'],
        selected: false,
        rootCommands: ['systemctl enable --now cockpit.socket'],
      },
      {
        id: 'ansible',
        name: 'Ansible',
        description: 'setupWizard.autoSoftware.ansible',
        packages: ['ansible'],
        selected: false,
      },
      {
        id: 'docker',
        name: 'Docker',
        description: 'setupWizard.autoSoftware.docker',
        packages: ['docker', 'docker-compose'],
        selected: false,
        rootCommands: ['systemctl enable --now docker.socket'],
      },
      {
        id: 'podman',
        name: 'Podman',
        description: 'setupWizard.autoSoftware.podman',
        packages: ['podman-docker', 'podman-compose', 'crun'],
        selected: false,
        rootCommands: ['systemctl enable --now podman.socket'],
        userCommands: ['systemctl --user enable --now podman.socket'],
      },
      {
        id: 'jenkins',
        name: 'Jenkins',
        description: 'setupWizard.autoSoftware.jenkins',
        packages: ['jenkins'],
        selected: false,
      },
      {
        id: 'puppet',
        name: 'Puppet',
        description: 'setupWizard.autoSoftware.puppet',
        packages: ['puppet'],
        selected: false,
      },
      {
        id: 'prometheus',
        name: 'Prometheus',
        description: 'setupWizard.autoSoftware.prometheus',
        packages: ['prometheus'],
        selected: false,
      },
      {
        id: 'terraform',
        name: 'Terraform',
        description: 'setupWizard.autoSoftware.terraform',
        packages: ['terraform'],
        selected: false,
      },
    ],
  },
  {
    id: 'gaming',
    name: 'setupWizard.autoCategories.gaming',
    items: [
      {
        id: 'aisleriot',
        name: 'Aisleriot',
        description: 'setupWizard.autoSoftware.aisleriot',
        packages: ['aisleriot'],
        selected: false,
      },
      {
        id: 'mari0',
        name: 'Mari0',
        description: 'setupWizard.autoSoftware.mari0',
        packages: ['mari0'],
        selected: false,
      },
      {
        id: 'kapman',
        name: 'Kapman',
        description: 'setupWizard.autoSoftware.kapman',
        packages: ['kapman'],
        selected: false,
      },
      {
        id: 'knights',
        name: 'Knights',
        description: 'setupWizard.autoSoftware.knights',
        packages: ['knights'],
        selected: false,
      },
      {
        id: 'kmahjongg',
        name: 'Kmahjongg',
        description: 'setupWizard.autoSoftware.kmahjongg',
        packages: ['kmahjongg'],
        selected: false,
      },
      {
        id: 'superTuxKart',
        name: 'Super Tux Kart',
        description: 'setupWizard.autoSoftware.superTuxKart',
        packages: ['supertuxkart'],
        selected: false,
      },
      {
        id: 'superTux',
        name: 'Super Tux',
        description: 'setupWizard.autoSoftware.superTux',
        packages: ['supertux'],
        selected: false,
      },
      {
        id: 'minetest',
        name: 'Minetest',
        description: 'setupWizard.autoSoftware.minetest',
        packages: ['minetest-git', 'minetest-server-git'],
        selected: false,
      },
      {
        id: '0ad',
        name: '0 A.D.',
        description: 'setupWizard.autoSoftware.0ad',
        packages: ['0ad'],
        selected: false,
      },
      {
        id: 'teeworlds',
        name: 'Teeworlds',
        description: 'setupWizard.autoSoftware.teeworlds',
        packages: ['teeworlds'],
        selected: false,
      },
      {
        id: 'xonotic',
        name: 'Xonotic',
        description: 'setupWizard.autoSoftware.xonotic',
        packages: ['xonotic'],
        selected: false,
      },
      {
        id: 'hedgewars',
        name: 'Hedgewars',
        description: 'setupWizard.autoSoftware.hedgewars',
        packages: ['hedgewars'],
        selected: false,
      },
    ],
  },
  {
    id: 'graphics',
    name: 'setupWizard.autoCategories.graphics',
    items: [
      {
        id: 'krita',
        name: 'Krita',
        description: 'setupWizard.autoSoftware.krita',
        packages: ['krita', 'krita-plugin-gmic', 'opencolorio'],
        selected: false,
      },
      {
        id: 'gimp',
        name: 'GIMP',
        description: 'setupWizard.autoSoftware.gimp',
        packages: ['gimp'],
        selected: false,
      },
      {
        id: 'inkscape',
        name: 'Inkscape',
        description: 'setupWizard.autoSoftware.inkscape',
        packages: ['inkscape'],
        selected: false,
      },
      {
        id: 'blender',
        name: 'Blender',
        description: 'setupWizard.autoSoftware.blender',
        packages: ['blender'],
        selected: false,
      },
      {
        id: 'digikam',
        name: 'Digikam',
        description: 'setupWizard.autoSoftware.digikam',
        packages: ['digikam'],
        selected: false,
      },
      {
        id: 'darktable',
        name: 'Darktable',
        description: 'setupWizard.autoSoftware.darktable',
        packages: ['darktable'],
        selected: false,
      },
      {
        id: 'luminanceHdr',
        name: 'Luminance HDR',
        description: 'setupWizard.autoSoftware.luminanceHdr',
        packages: ['luminancehdr'],
        selected: false,
      },
      {
        id: 'kolourpaint',
        name: 'Kolourpaint',
        description: 'setupWizard.autoSoftware.kolourpaint',
        packages: ['kolourpaint'],
        selected: false,
      },
      {
        id: 'myPaint',
        name: 'MyPaint',
        description: 'setupWizard.autoSoftware.myPaint',
        packages: ['mypaint'],
        selected: false,
      },
      {
        id: 'wings3d',
        name: 'Wings 3D',
        description: 'setupWizard.autoSoftware.wings3d',
        packages: ['wings3d'],
        selected: false,
      },
      {
        id: 'sweetHome3d',
        name: 'Sweet Home 3D',
        description: 'setupWizard.autoSoftware.sweetHome3d',
        packages: ['sweethome3d'],
        selected: false,
      },
      {
        id: 'freeCad',
        name: 'FreeCAD',
        description: 'setupWizard.autoSoftware.freeCad',
        packages: ['freecad'],
        selected: false,
      },
      {
        id: 'libreCad',
        name: 'LibreCAD',
        description: 'setupWizard.autoSoftware.libreCad',
        packages: ['librecad'],
        selected: false,
      },
      {
        id: 'kiCad',
        name: 'KiCad',
        description: 'setupWizard.autoSoftware.kiCad',
        packages: ['kicad'],
        selected: false,
      },
      {
        id: 'pencil2d',
        name: 'Pencil 2D',
        description: 'setupWizard.autoSoftware.pencil2d',
        packages: ['pencil2d'],
        selected: false,
      },
      {
        id: 'synfigStudio',
        name: 'Synfig Studio',
        description: 'setupWizard.autoSoftware.synfigStudio',
        packages: ['synfigstudio'],
        selected: false,
      },
      {
        id: 'openToonz',
        name: 'OpenToonz',
        description: 'setupWizard.autoSoftware.openToonz',
        packages: ['opentoonz'],
        selected: false,
      },
      {
        id: 'fontForge',
        name: 'FontForge',
        description: 'setupWizard.autoSoftware.fontForge',
        packages: ['fontforge'],
        selected: false,
      },
      {
        id: 'birdfont',
        name: 'Birdfont',
        description: 'setupWizard.autoSoftware.birdfont',
        packages: ['birdfont'],
        selected: false,
      },
    ],
  },
  {
    id: 'inputMethod',
    name: 'setupWizard.autoCategories.inputMethod',
    items: [
      {
        id: 'asian',
        name: 'Asian',
        description: 'setupWizard.autoSoftware.asian',
        packages: ['asian-fonts'],
        selected: false,
      },
      {
        id: 'indic',
        name: 'Indic (Devanagari, Tamil, etc.)',
        description: 'setupWizard.autoSoftware.indic',
        packages: ['fcitx5-m17n', 'fcitx5-configtool'],
        selected: false,
      },
      {
        id: 'simplifiedChinese',
        name: 'Simplified Chinese',
        description: 'setupWizard.autoSoftware.simplifiedChinese',
        packages: ['fcitx5-chinese-addons', 'fcitx5-configtool'],
        selected: false,
      },
      {
        id: 'traditionalChinese',
        name: 'Traditional Chinese',
        description: 'setupWizard.autoSoftware.traditionalChinese',
        packages: ['fcitx5-rime', 'fcitx5-configtool'],
        selected: false,
      },
      {
        id: 'japanese',
        name: 'Japanese',
        description: 'setupWizard.autoSoftware.japanese',
        packages: ['fcitx5-mozc', 'fcitx5-configtool'],
        selected: false,
      },
      {
        id: 'korean',
        name: 'Korean',
        description: 'setupWizard.autoSoftware.korean',
        packages: ['fcitx5-hangul', 'fcitx5-configtool'],
        selected: false,
      },
      {
        id: 'vietnamese',
        name: 'Vietnamese',
        description: 'setupWizard.autoSoftware.vietnamese',
        packages: ['fcitx5-unikey', 'fcitx5-configtool'],
        selected: false,
      },
      {
        id: 'sinhalese',
        name: 'Sinhalese',
        description: 'setupWizard.autoSoftware.sinhalese',
        packages: ['fcitx5-sayura', 'fcitx5-configtool'],
        selected: false,
      },
      {
        id: 'thai',
        name: 'Thai',
        description: 'setupWizard.autoSoftware.thai',
        packages: ['fcitx5-libthai', 'fcitx5-configtool'],
        selected: false,
      },
    ],
  },
  {
    id: 'internet',
    name: 'setupWizard.autoCategories.internet',
    items: [
      {
        id: 'xtreme',
        name: 'Xtreme',
        description: 'setupWizard.autoSoftware.xtreme',
        packages: ['xdman-beta-bin'],
        selected: false,
      },
      {
        id: 'fdm',
        name: 'FDM',
        description: 'setupWizard.autoSoftware.fdm',
        packages: ['freedownloadmanager'],
        selected: false,
      },
      {
        id: 'deluge',
        name: 'Deluge',
        description: 'setupWizard.autoSoftware.deluge',
        packages: ['deluge-gtk'],
        selected: false,
      },
      {
        id: 'qbittorrent',
        name: 'Qbittorrent',
        description: 'setupWizard.autoSoftware.qbittorrent',
        packages: ['qbittorrent'],
        selected: false,
      },
      {
        id: 'nextcloudClient',
        name: 'Nextcloud client',
        description: 'setupWizard.autoSoftware.nextcloudClient',
        packages: ['nextcloud-client'],
        selected: false,
      },
      {
        id: 'remmina',
        name: 'Remmina',
        description: 'setupWizard.autoSoftware.remmina',
        packages: ['remmina'],
        selected: false,
      },
      {
        id: 'filezilla',
        name: 'Filezilla',
        description: 'setupWizard.autoSoftware.filezilla',
        packages: ['filezilla'],
        selected: false,
      },
      {
        id: 'putty',
        name: 'Putty',
        description: 'setupWizard.autoSoftware.putty',
        packages: ['putty'],
        selected: false,
      },
      {
        id: 'warpinator',
        name: 'Warpinator',
        description: 'setupWizard.autoSoftware.warpinator',
        packages: ['warpinator'],
        selected: false,
      },
      {
        id: 'nitroshare',
        name: 'Nitroshare',
        description: 'setupWizard.autoSoftware.nitroshare',
        packages: ['nitroshare'],
        selected: false,
      },
    ],
  },
  {
    id: 'kernels',
    name: 'setupWizard.autoCategories.kernels',
    items: [
      {
        id: 'linuxLts',
        name: 'Linux LTS',
        description: 'setupWizard.autoSoftware.linuxLts',
        packages: ['linux-lts', 'linux-lts-headers'],
        selected: false,
      },
      {
        id: 'linuxHardened',
        name: 'Linux Hardened',
        description: 'setupWizard.autoSoftware.linuxHardened',
        packages: ['linux-hardened', 'linux-hardened-headers'],
        selected: false,
      },
      {
        id: 'linuxCachyosWithBore',
        name: 'Linux CachyOS with BORE',
        description: 'setupWizard.autoSoftware.linuxCachyosWithBore',
        packages: ['linux-cachyos', 'linux-cachyos-headers'],
        selected: false,
      },
      {
        id: 'linuxXanmod',
        name: 'Linux Xanmod',
        description: 'setupWizard.autoSoftware.linuxXanmod',
        packages: ['linux-xanmod-edge-x64v3', 'linux-xanmod-edge-x64v3-headers'],
        selected: false,
      },
      {
        id: 'linuxXanmodLts',
        name: 'Linux Xanmod LTS',
        description: 'setupWizard.autoSoftware.linuxXanmodLts',
        packages: ['linux-xanmod-lts', 'linux-xanmod-lts-headers'],
        selected: false,
      },
      {
        id: 'linuxMainline',
        name: 'Linux Mainline',
        description: 'setupWizard.autoSoftware.linuxMainline',
        packages: ['linux-mainline', 'linux-mainline-headers'],
        selected: false,
      },
    ],
  },
  {
    id: 'mail',
    name: 'setupWizard.autoCategories.mail',
    items: [
      {
        id: 'thunderbird',
        name: 'Thunderbird',
        description: 'setupWizard.autoSoftware.thunderbird',
        packages: ['thunderbird'],
        selected: false,
      },
      {
        id: 'kmail',
        name: 'Kmail',
        description: 'setupWizard.autoSoftware.kmail',
        packages: ['kmail'],
        selected: false,
      },
      {
        id: 'evolution',
        name: 'Evolution',
        description: 'setupWizard.autoSoftware.evolution',
        packages: ['evolution'],
        selected: false,
      },
      {
        id: 'geary',
        name: 'Geary',
        description: 'setupWizard.autoSoftware.geary',
        packages: ['geary'],
        selected: false,
      },
      {
        id: 'mailspring',
        name: 'Mailspring',
        description: 'setupWizard.autoSoftware.mailspring',
        packages: ['mailspring'],
        selected: false,
      },
      {
        id: 'clawsMail',
        name: 'Claws-mail',
        description: 'setupWizard.autoSoftware.clawsMail',
        packages: ['claws-mail'],
        selected: false,
      },
    ],
  },
  {
    id: 'multimedia',
    name: 'setupWizard.autoCategories.multimedia',
    items: [
      {
        id: 'hypnotix',
        name: 'Hypnotix',
        description: 'setupWizard.autoSoftware.hypnotix',
        packages: ['hypnotix'],
        selected: false,
      },
      {
        id: 'shortwave',
        name: 'Shortwave',
        description: 'setupWizard.autoSoftware.shortwave',
        packages: ['shortwave'],
        selected: false,
      },
      {
        id: 'converseen',
        name: 'Converseen',
        description: 'setupWizard.autoSoftware.converseen',
        packages: ['converseen'],
        selected: false,
      },
      {
        id: 'handbrake',
        name: 'Handbrake',
        description: 'setupWizard.autoSoftware.handbrake',
        packages: ['handbrake'],
        selected: false,
      },
      {
        id: 'mystiq',
        name: 'Mystiq',
        description: 'setupWizard.autoSoftware.mystiq',
        packages: ['mystiq'],
        selected: false,
      },
      {
        id: 'transmageddon',
        name: 'Transmageddon',
        description: 'setupWizard.autoSoftware.transmageddon',
        packages: ['transmageddon'],
        selected: false,
      },
      {
        id: 'soundConverter',
        name: 'SoundConverter',
        description: 'setupWizard.autoSoftware.soundConverter',
        packages: ['soundconverter'],
        selected: false,
      },
      {
        id: 'kodi',
        name: 'Kodi',
        description: 'setupWizard.autoSoftware.kodi',
        packages: ['kodi', 'kodi-platform', 'kodi-eventclients'],
        selected: false,
      },
      {
        id: 'mediaElch',
        name: 'MediaElch',
        description: 'setupWizard.autoSoftware.mediaElch',
        packages: ['mediaelch'],
        selected: false,
      },
      {
        id: 'subtitleComposer',
        name: 'Subtitle Composer',
        description: 'setupWizard.autoSoftware.subtitleComposer',
        packages: ['subtitlecomposer'],
        selected: false,
      },
      {
        id: 'kid3',
        name: 'Kid3',
        description: 'setupWizard.autoSoftware.kid3',
        packages: ['kid3'],
        selected: false,
      },
      {
        id: 'easytag',
        name: 'Easytag',
        description: 'setupWizard.autoSoftware.easytag',
        packages: ['easytag'],
        selected: false,
      },
      {
        id: 'k3b',
        name: 'K3B',
        description: 'setupWizard.autoSoftware.k3b',
        packages: ['k3b', 'cdparanoia', 'cdrdao', 'dvd+rw-tools', 'emovix', 'vcdimager', 'cdrtools'],
        selected: false,
      },
      {
        id: 'brasero',
        name: 'Brasero',
        description: 'setupWizard.autoSoftware.brasero',
        packages: ['brasero'],
        selected: false,
      },
      {
        id: 'xfburn',
        name: 'Xfburn',
        description: 'setupWizard.autoSoftware.xfburn',
        packages: ['xfburn'],
        selected: false,
      },
    ],
  },
  {
    id: 'office',
    name: 'setupWizard.autoCategories.office',
    items: [
      {
        id: 'libreOfficeFresh',
        name: 'LibreOffice Fresh',
        description: 'setupWizard.autoSoftware.libreOfficeFresh',
        packages: ['libreoffice-fresh', 'libmythes'],
        selected: false,
      },
      {
        id: 'libreOfficeStill',
        name: 'LibreOffice Still',
        description: 'setupWizard.autoSoftware.libreOfficeStill',
        packages: ['libreoffice-still', 'libmythes'],
        selected: false,
      },
      {
        id: 'joplin',
        name: 'Joplin',
        description: 'setupWizard.autoSoftware.joplin',
        packages: ['joplin-beta'],
        selected: false,
      },
      {
        id: 'onlyOffice',
        name: 'OnlyOffice',
        description: 'setupWizard.autoSoftware.onlyOffice',
        packages: ['onlyoffice-bin'],
        selected: false,
      },
      {
        id: 'wpsOffice',
        name: 'WPS Office',
        description: 'setupWizard.autoSoftware.wpsOffice',
        packages: ['wps-office', 'wps-office-mime', 'ttf-wps-fonts'],
        selected: false,
      },
      {
        id: 'freeOffice',
        name: 'FreeOffice',
        description: 'setupWizard.autoSoftware.freeOffice',
        packages: ['freeoffice'],
        selected: false,
      },
      {
        id: 'calligra',
        name: 'Calligra',
        description: 'setupWizard.autoSoftware.calligra',
        packages: ['calligra'],
        selected: false,
      },
      {
        id: 'obsidian',
        name: 'Obsidian',
        description: 'setupWizard.autoSoftware.obsidian',
        packages: ['obsidian'],
        selected: false,
      },
      {
        id: 'skrooge',
        name: 'Skrooge',
        description: 'setupWizard.autoSoftware.skrooge',
        packages: ['skrooge'],
        selected: false,
      },
      {
        id: 'kMyMoney',
        name: 'KMyMoney',
        description: 'setupWizard.autoSoftware.kMyMoney',
        packages: ['kmymoney'],
        selected: false,
      },
      {
        id: 'abiWord',
        name: 'AbiWord',
        description: 'setupWizard.autoSoftware.abiWord',
        packages: ['abiword'],
        selected: false,
      },
      {
        id: 'gnumeric',
        name: 'Gnumeric',
        description: 'setupWizard.autoSoftware.gnumeric',
        packages: ['gnumeric'],
        selected: false,
      },
      {
        id: 'gnuCash',
        name: 'GnuCash',
        description: 'setupWizard.autoSoftware.gnuCash',
        packages: ['gnucash'],
        selected: false,
      },
      {
        id: 'homebank',
        name: 'Homebank',
        description: 'setupWizard.autoSoftware.homebank',
        packages: ['homebank'],
        selected: false,
      },
    ],
  },
  {
    id: 'other',
    name: 'setupWizard.autoCategories.other',
    items: [
      {
        id: 'droidcam',
        name: 'Droidcam',
        description: 'setupWizard.autoSoftware.droidcam',
        packages: ['droidcam'],
        selected: false,
      },
      {
        id: 'soundwire',
        name: 'Soundwire',
        description: 'setupWizard.autoSoftware.soundwire',
        packages: ['soundwire'],
        selected: false,
      },
      {
        id: 'variety',
        name: 'Variety',
        description: 'setupWizard.autoSoftware.variety',
        packages: ['variety'],
        selected: false,
      },
      {
        id: 'conky',
        name: 'Conky',
        description: 'setupWizard.autoSoftware.conky',
        packages: ['conky', 'conky-manager2'],
        selected: false,
      },
      {
        id: 'keepassXc',
        name: 'KeePassXC',
        description: 'setupWizard.autoSoftware.keepassXc',
        packages: ['keepassxc'],
        selected: false,
      },
      {
        id: 'yakuake',
        name: 'Yakuake',
        description: 'setupWizard.autoSoftware.yakuake',
        packages: ['yakuake'],
        selected: false,
      },
    ],
  },
  {
    id: 'pkgmngrs',
    name: 'setupWizard.autoCategories.pkgmngrs',
    items: [
      {
        id: 'gnomeFirmware',
        name: 'GNOME Firmware',
        description: 'setupWizard.autoSoftware.gnomeFirmware',
        packages: ['gnome-firmware'],
        selected: false,
      },
      {
        id: 'appimagePool',
        name: 'Appimage Pool',
        description: 'setupWizard.autoSoftware.appimagePool',
        packages: ['appimagepool-appimage'],
        selected: false,
      },
      {
        id: 'octopi',
        name: 'Octopi',
        description: 'setupWizard.autoSoftware.octopi',
        packages: ['octopi'],
        selected: false,
      },
      {
        id: 'bauh',
        name: 'Bauh',
        description: 'setupWizard.autoSoftware.bauh',
        packages: ['bauh'],
        selected: false,
      },
      {
        id: 'discover',
        name: 'Discover',
        description: 'setupWizard.autoSoftware.discover',
        packages: ['discover', 'packagekit-qt6'],
        selected: false,
      },
      {
        id: 'gnomeSoftware',
        name: 'GNOME Software',
        description: 'setupWizard.autoSoftware.gnomeSoftware',
        packages: ['gnome-software'],
        selected: false,
      },
      {
        id: 'bazaar',
        name: 'Bazaar',
        description: 'setupWizard.autoSoftware.bazaar',
        packages: ['bazaar-git'],
        selected: false,
      },
    ],
  },
  {
    id: 'video',
    name: 'setupWizard.autoCategories.video',
    items: [
      {
        id: 'kdenlive',
        name: 'Kdenlive',
        description: 'setupWizard.autoSoftware.kdenlive',
        packages: ['kdenlive', 'movit', 'sox', 'opus-tools', 'frei0r-plugins', 'opentimelineio', 'dvgrab', 'opencv'],
        selected: false,
      },
      {
        id: 'dragon',
        name: 'Dragon',
        description: 'setupWizard.autoSoftware.dragon',
        packages: ['dragon'],
        selected: false,
      },
      {
        id: 'shotcut',
        name: 'Shotcut',
        description: 'setupWizard.autoSoftware.shotcut',
        packages: ['shotcut'],
        selected: false,
      },
      {
        id: 'obsStudio',
        name: 'OBS Studio',
        description: 'setupWizard.autoSoftware.obsStudio',
        packages: ['obs-studio'],
        selected: false,
      },
      {
        id: 'vlc',
        name: 'VLC',
        description: 'setupWizard.autoSoftware.vlc',
        packages: ['vlc'],
        selected: false,
      },
      {
        id: 'smPlayer',
        name: 'SMPlayer',
        description: 'setupWizard.autoSoftware.smPlayer',
        packages: ['smplayer', 'smplayer-skins', 'smplayer-themes'],
        selected: false,
      },
      {
        id: 'bakaMplayer',
        name: 'Baka-Mplayer',
        description: 'setupWizard.autoSoftware.bakaMplayer',
        packages: ['baka-mplayer'],
        selected: false,
      },
    ],
  },
  {
    id: 'virtualization',
    name: 'setupWizard.autoCategories.virtualization',
    items: [
      {
        id: 'virtualBox',
        name: 'VirtualBox',
        description: 'setupWizard.autoSoftware.virtualBox',
        packages: ['virtualbox-meta'],
        selected: false,
        icon: 'virtualbox',
      },
      {
        id: 'gnomeBoxes',
        name: 'GNOME Boxes',
        description: 'setupWizard.autoSoftware.gnomeBoxes',
        packages: ['gnome-boxes'],
        selected: false,
        rootCommands: ['systemctl enable --now libvirtd'],
      },
      {
        id: 'virtManager',
        name: 'Virtual Machine Manager',
        description: 'setupWizard.autoSoftware.virtManager',
        packages: ['virt-manager-meta'],
        selected: false,
        icon: 'virt-manager',
        rootCommands: ['systemctl enable --now libvirtd'],
      },
      {
        id: 'genymotion',
        name: 'Genymotion',
        description: 'setupWizard.autoSoftware.genymotion',
        packages: ['genymotion', 'virtualbox-meta'],
        selected: false,
      },
    ],
  },
];
